from typing import Protocol, List, Optional
from .models import Rule

class RuleRepository(Protocol):
    async def get_rule(self, rule_id: str, version: Optional[int] = None) -> Rule: ...
    async def save_rule(self, rule_id: str, source: str, language_version: int) -> Rule: ...
    async def list_rules(self, status: Optional[str] = None) -> List[Rule]: ...
    async def archive_rule(self, rule_id: str) -> None: ...
    async def activate_rule(self, rule_id: str, version: int) -> Rule: ...
