from typing import Protocol, List, Optional
from .models import Rule

class RuleRepository(Protocol):
    def get_rule(self, rule_id: str, version: Optional[int] = None) -> Rule: ...
    def save_rule(self, rule_id: str, source: str, language_version: int) -> Rule: ...
    def list_rules(self, status: Optional[str] = None) -> List[Rule]: ...
    def delete_rule(self, rule_id: str) -> None: ...
